begin implementing the kybra extension
demergent-labs/kybra pull request #487
Opened 2024-04-24 16:59 UTC by lastmjs

2024-04-24 20:36 UTC, lastmjs commented on .github/workflows/test.yml
> +              run: source venv/bin/activate && python -m kybra install-dfx-extension
Same question for me as in Azle, should we automatically install this? I'm waiting on some guidance for this, we might be able to do this automatically soon...we just need to be able to run dfx start in the same directory as a dfx.json file with an unsupported extension

2024-04-24 20:36 UTC, lastmjs commented on kybra/__main__.py
> +    did_path = os.environ.get("CANISTER_CANDID_PATH", "CANDID_PATH_NOT_FOUND")
Should we throw if this is not found?

2024-04-24 20:36 UTC, lastmjs commented on kybra/__main__.py
> +    if sys.argv[1] == "install-dfx-extension":
Should I comment that this is temporary? Or explain that a more official way to install is coming?

2024-04-24 20:36 UTC, lastmjs commented on kybra/compiler/dfx_extension/extension.json
> +    "version": "0.0.0",
How should versioning work? If this matches the version of kybra then we'll never have confusion about which version is which...we should get this to update automatically then in our publish script or something

2024-04-24 20:36 UTC, lastmjs commented on kybra/compiler/dfx_extension/extension.json
> +    "keywords": [],
update this metadata later, make an issue for it here and in azle

2024-04-24 20:36 UTC, lastmjs commented on kybra/compiler/dfx_extension/install.sh
> +dfx cache install
Do we need to run dfx cache install? It erases any other unofficial extensions

2024-04-25 14:39 UTC, lastmjs commented on kybra/__main__.py
> +    if sys.argv[1] == "install-dfx-extension":
Comment added

2024-04-25 21:54 UTC, bdemann requested changes

2024-04-25 21:54 UTC, bdemann commented on kybra/__main__.py
> +    did_path = os.environ.get("CANISTER_CANDID_PATH", "CANDID_PATH_NOT_FOUND")
Maybe, lets talk about it

2024-04-26 11:09 UTC, lastmjs commented on kybra/__main__.py
> +    did_path = os.environ.get("CANISTER_CANDID_PATH", "CANDID_PATH_NOT_FOUND")
Done

2024-04-26 11:33 UTC, merged